### ISSUE TITLE
Support require.resolve

### ISSUE THREAD

**Issue by chengjianhua** [trayio/babel-plugin-webpack-alias#41]
I use this plugin in mocha tests. it's nice to resolve the path with alias when I use `require()` or `import`. But I have some special requirements that I need to use the alias path be a parameter for a   function [`mock-require()`](https://github.com/boblauer/mock-require). Obviously, it doesn't work. Maybe in some cases, we can use `require.resolve()` to get the real path corresponds to the alias. Thanks for your works, it's awesome!

**Comment by strctr** [comment]
Eah, have the same issue. `require.resolve` isn't processed by this plugin.

**Comment by chengjianhua** [comment]
This is inactive.
