### ISSUE TITLE
Support resolve.extensions

### ISSUE THREAD

**Issue by tshelburne** [trayio/babel-plugin-webpack-alias#5]
Would be nice to be able to do the following:

```javascript
const Nav = require('ui/components/navigation')
// instead of 
const Nav = require('ui/components/navigation.jsx')
```

**Comment by Lokua** [comment]
+1

**Comment by adriantoine** [comment]
It would be a nice improvement, feel free to submit a PR.

**Comment by adriantoine** [comment]
`resolve.extensions` is now supported! See [v1.8.0](https://github.com/trayio/babel-plugin-webpack-alias/releases/tag/v1.8.0)

**Comment by tshelburne** [comment]
@adriantoine Awesome, thanks for the update!
