### ISSUE TITLE
Cannot find module "..." when module is immediately used

### ISSUE THREAD

**Issue by tshelburne** [trayio/babel-plugin-webpack-alias#6]
This is probably related to #5.

The following will fail with `Error: Cannot find module '../higher-order/activateable'`:

```javascript
import Activateable from 'ui/higher-order/activateable';

const SectionElement = Activateable("section")
```

If I add the extension to activeatable, it works:

```javascript
import Activateable from 'ui/higher-order/activateable.jsx';

const SectionElement = Activateable("section")
```

**Comment by adriantoine** [comment]
Yeah, the extensions are not support at the moment, I can have a look, feel free to submit a PR!

**Comment by tshelburne** [comment]
@adriantoine I'll look at doing that - I called this one out specifically because it's not actually requiring the extensions in *all* of my non-test code, only in certain files. Seems intermittent. I'll dig in and see what I can do though.

**Comment by adriantoine** [comment]
`resolve.extensions` is now supported! See [v1.8.0](https://github.com/trayio/babel-plugin-webpack-alias/releases/tag/v1.8.0)
