### ISSUE TITLE
Example using mocha?

### ISSUE THREAD

**Issue by chapati23** [trayio/babel-plugin-webpack-alias#8]
hi, this plugin looks like it does exactly what i need. unfortunately i can't get it to go with mocha :-/

my `npm test` that runs mocha looks like this:
```BABEL_DISABLE_CACHE=1 NODE_ENV=test mocha 'src/**/*.spec.js' --recursive --compilers js:babel-register --require ./src/lib/testsetup.js --require ignore-styles```

and my `.babelrc` looks like this:
```json
{
  "presets": ["es2015", "stage-0", "react"],
  "env": {
    "test": {
      "plugins": [
        [
          "babel-plugin-webpack-alias",
          { "config": "./webpack.config.babel.js" }
        ],
        [
          "babel-plugin-webpack-loaders",
          {
            "config": "./webpack.config.babel.js",
            "verbose": false
          }
        ]
      ]
    }
  }
}
```

my webpack resolve-section:
```js
    resolve: {
      alias: {
        src: __dirname + '/src',
        shared: __dirname + '/src/components/shared'
      }
    }
```

i tried this for importing:
```js
import bla from 'shared/bla'
import bla from 'shared/bla.js'
```

both fails unfortunately with `Error: Cannot find module 'shared/bla.js'`

what am i doing wrong? working example using mocha would be awesome :)

**Comment by AStaroverov** [comment]
same problem

**Comment by adriantoine** [comment]
Hi! your setup looks fine, we're using it on different part of our application using Mocha and AVA. I'll provide a working sample project on GitHub.

**Comment by chapati23** [comment]
thad would be fantastic :)

**Comment by isomoar** [comment]
I'm pretty sure there is nothing wrong with test framework but with plugin. `shared/bla.js` is wrong path, it must be resolved and look like `./shared/bla.js`. There is already a PR that solved this issue https://github.com/trayio/babel-plugin-webpack-alias/pull/10

**Comment by chapati23** [comment]
tried that PR, still the same problem unfortunately

**Comment by adriantoine** [comment]
Hi,

Same as for the other issues, sorry for the delay, we have been quite busy recently at tray.io, here is a repo with minimal examples using `babel-plugin-webpack-alias`: https://github.com/adriantoine/babel-plugin-webpack-alias-examples

**Comment by adriantoine** [comment]
@AStaroverov @chapati23

**Comment by ijpiantanida** [comment]
Something seems to be broken.

Cloned that example, and I'm getting this error:
`The resolved config file doesn't contain a resolve configuration`.

**Comment by adriantoine** [comment]
Hi @ijpiantanida, I'm having a look

**Comment by adriantoine** [comment]
@ijpiantanida this a bit weird, I first had the same issue, then I was changing things around and it somehow fixed itself 🤔 Can you try clearing `node_modules` and any node cache and try again?

**Comment by ijpiantanida** [comment]
Same result.
It also happened to me in another project I was just setting up, that's why I ended up here.

What I've found is that the webpakc config file require is returning an empty object. But if you change it to have only static values, like:
```
module.exports = {
    resolve: {
        alias: {
            'alias': '/Users/ignacio/projects/babel-plugin-webpack-alias-examples/mocha/deep/folder/alias',
        }
    }
};
```
then the config is read, although the module still can't be found (`Cannot find module 'deep/folder/alias').

I tried both on node v6.4.0 and v4.5.0 just in case.

**Comment by ijpiantanida** [comment]
Just to rule out any environment issue, I dockerized everything under `node:argon` and the issue persists.

**Comment by adriantoine** [comment]
That's interesting, let's continue this discussion here https://github.com/adriantoine/babel-plugin-webpack-alias-examples/issues/1 @ijpiantanida

**Comment by adriantoine** [comment]
Running the mocha test with the env variable `BABEL_DISABLE_CACHE` set to `1` allows to reproduce the issue all the time.

```bash
BABEL_DISABLE_CACHE=1 mocha --compilers js:babel-register
```
